version: "3.8"

services:
  postgres:
    image: "postgres:10.5"
    network_mode: bridge
    container_name: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
  web:
    build: .
    network_mode: bridge
    expose:
      - 8080
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  postgres-data: